name: cheez_admin_app
description: Admin app for Cheez n' Cream Co.
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase (use these exact versions)
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  fluttertoast: ^9.0.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  path_provider: ^2.1.1
  path: ^1.8.3
  pdf: ^3.11.1
  printing: ^5.13.3
  share_plus: ^10.1.2
  url_launcher: ^6.2.5
  flutter_dotenv: ^5.1.0
  webview_flutter: ^4.4.2
  cross_file: ^0.3.4
  screenshot: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - .env
  
  # Fonts
  fonts:
    - family: Mirador
      fonts:
        - asset: assets/fonts/mirador-extralight.otf
          weight: 200
        - asset: assets/fonts/mirador-light.otf
          weight: 300
        - asset: assets/fonts/mirador-regular.otf
          weight: 400
        - asset: assets/fonts/mirador-medium.otf
          weight: 500
        - asset: assets/fonts/mirador-semibold.otf
          weight: 600
        - asset: assets/fonts/mirador-bold.otf
          weight: 700
        - asset: assets/fonts/mirador-extrabold.otf
          weight: 800
        - asset: assets/fonts/mirador-heavy.otf
          weight: 900
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Thin.ttf
          weight: 100
        - asset: assets/fonts/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit-Black.ttf
          weight: 900

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/logoapp.png"
  adaptive_icon_background: "#7E8EAA"
  adaptive_icon_foreground: "assets/icons/logoapp.png"
# dependencies:
#   flutter:
#     sdk: flutter
#   firebase_core: latest
#   cloud_firestore: latest
#   firebase_auth: latest
#   intl: latest
